backend:
  # name: test-repo
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

# Uncomment local_backend when you need to develop in your local
local_backend: true # run npx netlify-cms-proxy-server for local testing
logo_url: https://toddlambert.myresume.site/assets/logo-long.webp
media_folder: "static/assets"
public_folder: "/assets"

collections:
  - name: "Portfolio" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Portfolio" # Used in the UI
    label_singular: "Post" # Used in the UI, ie: "New Post"
    description: >
      Create your portfolio here. Add images, youtube videos, layer multimedia svgs over image and video. Its a playground for your work. 
    folder: "src/content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} — {{year}}/{{month}}/{{day}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: "Template",
          name: "template",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          hint: "Start slug with /. Use only alphanumeric characters, - and _. Avoid spaces in any cases.",
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - { label: "SEO Description", name: "description", widget: "text" }
      - { label: "YouTube Url", name: "youtuber", widget: "string", required: false }
      - { label: "YouTube AutoPlay", name: "youtubeautoplay", widget: "boolean", default: "false", required: false }
      - { label: "YouTube Mute", name: "youtubemute", widget: "boolean", default: "true", required: false }
      - { label: "YouTube Show Controls", name: "youtubecontrols", widget: "boolean", default: "false", required: false }
      - { label: "YouTube Start", name: "youtubestart", widget: "string", hint: "This is measured in seconds - 32 would start the video at the 32-second mark", required: false }
      - { label: "YouTube End", name: "youtubeend", widget: "string", hint: "This is measured in seconds - 102 would end the video at the 1-min  and 42-second mark", required: false }
      - { label: "Make Post Shareable?", name: "sharethis:", widget: "boolean", default: "true", required: false }
      # - { label: "Allow Comments?", name: "comments:", widget: "boolean", default: "true", required: false }
      # - { label: "Sign Up Box", name: "signup", widget: "boolean",
      #      default: "false", required: false }
  

      
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: "image",
          hint: "The primary image used for all social media, blog previews and the feature image at the top of the post",
          tagname: "",
        }
      - {
          label: "Underlay Image",
          name: "underlayImage",
          widget: "image",
          hint: "This puts a background image behind the profile section of the site",
          required: false,
          tagname: "",
        }
      - {
          label: "SVG",
          name: "svgImage",
          widget: "image",
          hint: "This is the animation layer where your animated or static SVG image goes - it is on the top of the stack",
          required: false,
          tagname: "",
        }
      - { label: "SVG Z-Index", name: "svgzindex", widget: "string", required: false, tagname: "", }



      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          hint: "Main content goes here.",
          required: false
        }
  - label: "Pages"
    name: "pages"
    description: >
      Edit your home page. resume and cover letter here. You can also edit the privacy, terms and disclaimers and contact pages.
    files:
      - label: "Profile and Resume"
        name: "home"
        file: "src/content/pages/index.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "index-page",
            }



   


          - { label: "Slug", name: "slug", widget: "hidden", default: "/" }
          - { label: "Page and SEO Title", name: "title", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Featured Image", name: "featuredImage", widget: "image" }
          - { label: "YouTube Url", name: "youtuber", hint: "Add YouTube video to hero section", widget: "string", required: false }
          - { label: "Profile/Avatar", name: "secondaryImage", widget: "image", hint: "This is your profile picture or avatar", required: false }
          - { label: "Profile Background", name: "underlayImage", widget: "image", hint: "This is your profile section background", required: false }
          

          - { label: "Profile Title", name: "profTitle", widget: "string",
           required: false }

          - { label: "Profile text (intro)", name: "profText", widget: "markdown", required: false }

          - { label: "Audio - YouTube Url", name: "youtuber2", hint: "Paste YouTube Url of song you wish to play on the site", widget: "string", required: false }
          - { label: "Audio - Title", name: "audiotitle", hint: "Artist Name - Track Title", widget: "string", required: false }

          - { label: "Your Address", name: "addressText", widget: "string", required: false }
          - { label: "Your Address 2", name: "addressText2", widget: "string", required: false }

          - { label: "Portfolio Spotlight", name: "openQuote", widget: "markdown",
           required: false }

          - { label: "Portfolio Quote - Closing", name: "closeQuote", widget: "markdown",
           required: false }

          


          - { label: "Resume", name: "body", widget: "markdown" }


          - label: "Cover Letter Link"
            name: "coverletter"
            widget: "object"
            fields:
              - name: "coverText"
                label: "Link Text"
                widget: "string"
              - name: "coverLink"
                label: "Custom Link"
                widget: "string"
                required: false 

          - label: "Contact Button"
            name: "cta"
            widget: "object"
            fields:
              - name: "ctaText"
                label: "Button text"
                widget: "string"
              - name: "ctaLink"
                label: "Custom Link"
                widget: "string"
                required: false

      - label: "Cover Letter"
        name: "cover"
        file: "src/content/pages/about.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/skills" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Skills"
        name: "skill"
        file: "src/content/pages/skills.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "skills-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/notes" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Interview Notes"
        name: "notes"
        file: "src/content/pages/notes.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "notes-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/cover" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "src/content/pages/contact.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "contact-page",
            }
          - {
              label: "Slug",
              name: "slug",
              widget: "hidden",
              default: "/contact",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Disclaimer"
        name: "disclaimer"
        file: "src/content/pages/disclaimer.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "disclaimer-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/disclaimer" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Privacy"
        name: "privacy"
        file: "src/content/pages/privacy.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "privacy-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/privacy" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Terms of Use"
        name: "terms"
        file: "src/content/pages/terms.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "terms-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/terms" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: settings
    label: Settings
    description: >
      Modify all of the various settings for your site, such as SEO, default images, and Analytics account, social accounts, etc.
    files:
      - name: general
        label: General
        file: "src/util/site.json"
        fields:
          - label: meta
            name: meta
            widget: object
            fields:
              - widget: string
                name: title
                label: Site Title
                required: true
              - widget: hidden
                name: titleTemplate
                label: Title Template (ignore)
                default: "%s"
                required: true
              - widget: string
                name: siteUrl
                label: Website URL
                required: true
              - widget: text
                name: description
                label: SEO Description
                default: ""
                required: false

              - widget: image
                name: image
                label: Default Image
                hint: "This image is used for social/search previews of the site and its posts"
                required: true
                default: "/assets/default-background.webp"

              - widget: image
                name: iconimage
                required: false
                label: Your Logo

              - widget: image
                name: favicon16x16
                label: Site Favicon 16x16 (name image like 'favicon-16x16.png')
                hint: "You can use the same 512x512 image for all at the expense of users with slower connections"
                default: "/assets/favicon-16x16.png"

              # - widget: image
              #   name: favicon32x32
              #   label: Site Favicon 32x32 (name image like 'favicon-16x16.png')
              #   hint: "You can use the same 512x512 image for all at the expense of users with slower connections"
              #   default: "/assets/favicon-32x32.png"
              # - widget: image
              #   name: icon192
              #   label: Site Icon 192x192 (name image like 'icon-192x192.png')
              #   hint: "You can use the same 512x512 image for all at the expense of users with slower connections"
              #   default: "/assets/icon-192x192.png"
              # - widget: image
              #   name: icon512
              #   label: Site Icon 512x512 (name image like 'icon-512x512.png')
              #   hint: "You can use the same 512x512 image for all at the expense of users with slower connections"
              #   default: "/assets/icon-512x512.png"

              - widget: string
                name: twitterUsername
                label: Twitter user (no '@' justthename)
                required: false
              - widget: string
                name: companyname
                label: Your Name
                required: true
              - widget: boolean
                name: showfooter
                label: Show the Footer
                required: false
              - widget: boolean
                name: showFeature
                label: Show Feature
                required: false
              - widget: boolean
                name: showInfo
                label: Show Profile
                required: false
              - widget: boolean
                name: showPosts
                label: Show Portfolio/Posts
                required: false
              - widget: boolean
                name: showSocial
                label: Show Social Links
                required: false
              - widget: boolean
                name: showSkills
                label: Show Skills
                required: false
              - widget: boolean
                name: showResume
                label: Show Resume
                required: false
              - widget: boolean
                name: showCover
                label: Show Cover Letter
                required: false

              - widget: boolean
                name: showNav
                label: Show Nav Bar at top
                default: true
                required: false
              - widget: boolean
                name: showNav2
                label: Show floating Nav Bar on side
                default: true
                required: false

              - widget: string
                name: menu1
                label: Menu - Profile Title
                default: "Profile"
                required: false
              - widget: string
                name: menu2
                label: Menu - Posts/Portfolio Title
                default: "Posts"
                required: false
              - widget: string
                name: menu3
                label: Menu - Resume Title
                default: "Resume"
                required: false
              - widget: string
                name: menu4
                label: Menu - Skills Title
                default: "Skills"
                required: false


               

  
          - label: "Commenting – Go to: https://commentbox.io - sign up for free account "
            name: comments
            widget: string
            hint: "Add your CommentBox ID – should look like xxxxxxxxxxxxxxxx-proj"
            required: false
          - label: "Google Analytics"
            name: ga
            widget: string
            hint: "Add your tracking ID, should look like UA-XXXXXXXXX-X or G-XXXXXXXXXX"
      - label: Social Icons
        name: socialIcons
        file: "src/util/socialmedia.json"
        fields:
          - label: Social Icons
            name: socialIcons
            widget: list
            collapsed: true
            hint: "Here you can add social icons, Click on 'Add social icons'"
            fields:
              - label: "Icons"
                name: "icon"
                widget: "select"
                options:
                  [
                    "facebook",
                    "twitter",
                    "linkedin",
                    "youtube",
                    "instagram",
                    "rss",
                    "github",
                    "telegram",
                    "pinterest",
                    "snapchat",
                    "skype",
                    "wordpress",
                    "dribbble",
                    "medium",
                    "behance",
                    "vk",
                  ]
                hint: "Select the Icon"
              - widget: string
                name: url
                label: url
                required: true
                hint: "Paste the 'URL' of your Social media"

